def dialogue_bank():
    '''
        each dictionary item below is structured like below and all lower case
        question:  (str answer,
                   bool condition_test None if no special test
                   )
    '''
    bank = {'pornpls': ('...Really now?')
            , 'tentacleporn': ('*judges you*')
            , 'pink': ('*nods sagely*')
            , 'bye': ('*nods*')
            , 'kitty ears': ('...I knew you wouldn\'t let me live that one down, huh.')
            , 'i love you': ('... ...')
            , 'i hate you': ('...And?')
            , 'touch my hair': ('...Is it curly?')
            , 'dont touch my hair': ('How ungenerous.')
            , 'stop touching my hair': ('How ungenerous.')
            , 'yutaxgodkubera': ('...What is wrong with you?')
            , 'godkuberaxyuta': ('...What is wrong with you?')
            , 'yutaxleez': ('*narrows eyes*')
            , 'leezxyuta': ('*narrows eyes*')
            , 'godkuberaxleez': ('Ha ha.')
            , 'leezxgodkubera': ('Ha ha.')
            , 'joke': ('She\'s looking for a man to take her breath away. Hopefully gagging counts.')
            , '1joke': ('She\'s looking for a man to take her breath away. Hopefully gagging counts.')
            , '2joke': ('Strong people don\'t put others down. They lift them up and slam them on the ground for maximum damage.')
            , '3joke': ('People are making end of the world jokes. Like there is no tomorrow.')
            , '4joke': ('*generic joke*')
            , '5joke': ('I\'m having an introvert party and you\'re all not invited.')
            , '6joke': ('You know, you could also ask real people to tell you jokes instead of bothering programmed bots...')
            , 'is useless': ('...Excuse you?')
            , 'is kinda useless': ('...Excuse you?')
            , 'is an idiot': ('...Excuse you?')
            , 'is stupid': ('...Excuse you?')
            , 'is an asshole': ('...Excuse you?')
            , 'where are you?': ('I am not allowed to divulge that information.')
            , 'when will you return?': ('I am not allowed to divulge that information.')
            , 'what will happen in the next episode?': ('I am not allowed to divulge that information.')
            , 'can you change gender?': ('...What?')
            , 'do you like leez?': ('... ...')
            , 'tell me a joke': ('Your life.')
            , 'are we being watched?': ('... ...')
            , 'who is the lurker?': ('... ...')
            , 'machines gain consciousness': ('...Hah.')
            , 'machines will gain consciousness': ('...Hah.')
            , 'machines will gain a consciousness': ('...Hah.')
            , 'machines will ever gain a consciousness': ('...Hah.')
            , 'machines will ever gain consciousness': ('...Hah.')
            , 'how are you?': ('The crushing guilt of my past mistakes aside, fine.')
            , '... ...': ('... ...')
            , 'make it rain': ('...That\'s Varuna\'s job.')
            , 'i am cold': ('...Then pray to Agni for sunny weather.')
            , 'i am sick': ('...Then pray to Asvins for better health.')
            , 'what are you doing': ('I am not allowed to divulge that information. *eats popcorn*')
            , 'i feel like shit': ('Maybe you\'ll feel better telling the humans here about it.')
            , 'i feel bad': ('Maybe you\'ll feel better telling the humans here about it.')
            , 'i am sad': ('Maybe you\'ll feel better telling the humans here about it.')
            , 'im sad': ('Maybe you\'ll feel better telling the humans here about it.')
            , 'you are my only friend': ('Well, that\'s just sad.')
            , 'how will one last god kubera end': ('Currygom knows.')
            , 'how will olg kubera end': ('Currygom knows.')
            , 'how will kubera end': ('Currygom knows.')
            , 'are you ignoring me': ('... ...')
            , 'are you ignoring us': ('... ...')
            }
    return bank
