def dialogue_bank():
    '''
        each dictionary item below is structured like below and all lower case
        question:  (str answer,
                   bool condition_test None if no special test
                   )
    '''
    bank = {'pornpls': ('...really now?', None)
            , 'tentacleporn': ('*judges you*', None)
            , 'pink': ('*nods sagely*', None)
            , 'bye': ('*nods*', None)
            , 'kitty ears': ('...i knew you wouldn\'t let me live that one down, huh.', None)
            , 'i love you': ('... ...', None)
            , 'touch my hair': ('...is it curly?', None)
            , 'dont touch my hair': ('how ungenerous.', None)
            , 'stop touching my hair': ('how ungenerous.', None)
            , 'yutaxgodkubera': ('...what is wrong with you?', None)
            , 'godkuberaxyuta': ('...what is wrong with you?', None)
            , 'yutaxleez': ('*narrows eyes*', None)
            , 'leezxyuta': ('*narrows eyes*', None)
            , 'godkuberaxleez': ('ha ha.', None)
            , 'leezxgodkubera': ('ha ha.', None)
            , 'joke': ('she\'s looking for a man to take her breath away. hopefully gagging counts.', None)
            , '2joke': ('strong people don\'t put others down. they lift them up and slam them on the ground for maximum damage.', None)
            , '3joke': ('people are making end of the world jokes. like there is no tomorrow.', None)
            , '5joke': ('i\'m having an introvert party and you\'re all not invited.', None)
            , '6joke': ('you know, you could also ask real people to tell you jokes instead of bothering programmed bots...', None)
            , 'is useless': ('...excuse you?', None)
            , 'is kinda useless': ('...excuse you?', None)
            , 'is an idiot': ('...excuse you?', None)
            , 'is stupid': ('...excuse you?', None)
            , 'is an asshole': ('...excuse you?', None)
            , 'where are you?': ('i am not allowed to divulge that information.', None)
            , 'when will you return?': ('i am not allowed to divulge that information.', None)
            , 'what will happen in the next episode?': ('i am not allowed to divulge that information.', None)
            , 'can you change gender?': ('...what?', None)
            , 'do you like leez?': ('... ...', None)
            , 'tell me a joke': ('your life.', None)
            , 'are we being watched?': ('... ...', None)
            , 'who is the lurker?': ('... ...', None)
            , 'machines gain consciousness': ('...hah.', None)
            , 'machines will gain consciousness': ('...hah.', None)
            , 'machines will gain a consciousness': ('...hah.', None)
            , 'machines will ever gain a consciousness': ('...hah.', None)
            , 'machines will ever gain consciousness': ('...hah.', None)
            , 'how are you?': ('the crushing guilt of my past mistakes aside, fine.', None)
            , '... ...': ('... ...', None)
            , 'make it rain': ('...that\'s varuna\'s job.', None)
            , 'i am cold': ('...then pray to agni for sunny weather.', None)
            , 'i am sick': ('...then pray to asvins for better health.', None)
            , 'what are you doing': ('i am not allowed to divulge that information. *eats popcorn*', None)
            , 'i feel like shit': ('maybe you\'ll feel better telling the humans here about it.', None)
            , 'i feel bad': ('maybe you\'ll feel better telling the humans here about it.', None)
            , 'i am sad': ('maybe you\'ll feel better telling the humans here about it.', None)
            , 'im sad': ('maybe you\'ll feel better telling the humans here about it.', None)
            , 'you are my only friend': ('well, that\'s just sad.', None)
            , 'how will one last god kubera end': ('currygom knows.', None)
            , 'how will one last god kubera end': ('currygom knows.', None)
            , 'how will olg kubera end': ('currygom knows.', None)
            , 'how will kubera end': ('currygom knows.', None)
            }
    return bank
