def dialogue_bank():
    '''
        each dictionary item below is structured like below and all lower case
        question:  (str answer,
                   bool condition_test None if no special test
                   )
    '''
    bank = {'pornpls': ('...Really now?', None)
            , 'tentacleporn': ('*judges you*', None)
            , 'pink': ('*nods sagely*', None)
            , 'bye': ('*nods*', None)
            , 'kitty ears': ('...I knew you wouldn\'t let me live that one down, huh.', None)
            , 'i love you': ('... ...', None)
            , 'i hate you': ('...And?', None)
            , 'touch my hair': ('...Is it curly?', None)
            , 'dont touch my hair': ('How ungenerous.', None)
            , 'stop touching my hair': ('How ungenerous.', None)
            , 'yutaxgodkubera': ('...What is wrong with you?', None)
            , 'godkuberaxyuta': ('...What is wrong with you?', None)
            , 'yutaxleez': ('*narrows eyes*', None)
            , 'leezxyuta': ('*narrows eyes*', None)
            , 'godkuberaxleez': ('Ha ha.', None)
            , 'leezxgodkubera': ('Ha ha.', None)
            , 'joke': ('She\'s looking for a man to take her breath away. Hopefully gagging counts.', None)
            , '2joke': ('Strong people don\'t put others down. They lift them up and slam them on the ground for maximum damage.', None)
            , '3joke': ('People are making end of the world jokes. Like there is no tomorrow.', None)
            , '4joke': ('*generic joke*')
            , '5joke': ('I\'m having an introvert party and you\'re all not invited.', None)
            , '6joke': ('You know, you could also ask real people to tell you jokes instead of bothering programmed bots...', None)
            , 'is useless': ('...Excuse you?', None)
            , 'is kinda useless': ('...Excuse you?', None)
            , 'is an idiot': ('...Excuse you?', None)
            , 'is stupid': ('...Excuse you?', None)
            , 'is an asshole': ('...Excuse you?', None)
            , 'where are you?': ('I am not allowed to divulge that information.', None)
            , 'when will you return?': ('I am not allowed to divulge that information.', None)
            , 'what will happen in the next episode?': ('I am not allowed to divulge that information.', None)
            , 'can you change gender?': ('...What?', None)
            , 'do you like leez?': ('... ...', None)
            , 'tell me a joke': ('Your life.', None)
            , 'are we being watched?': ('... ...', None)
            , 'who is the lurker?': ('... ...', None)
            , 'machines gain consciousness': ('...Hah.', None)
            , 'machines will gain consciousness': ('...Hah.', None)
            , 'machines will gain a consciousness': ('...Hah.', None)
            , 'machines will ever gain a consciousness': ('...Hah.', None)
            , 'machines will ever gain consciousness': ('...Hah.', None)
            , 'how are you?': ('The crushing guilt of my past mistakes aside, fine.', None)
            , '... ...': ('... ...', None)
            , 'make it rain': ('...That\'s Varuna\'s job.', None)
            , 'i am cold': ('...Then pray to Agni for sunny weather.', None)
            , 'i am sick': ('...Then pray to Asvins for better health.', None)
            , 'what are you doing': ('I am not allowed to divulge that information. *eats popcorn*', None)
            , 'i feel like shit': ('Maybe you\'ll feel better telling the humans here about it.', None)
            , 'i feel bad': ('Maybe you\'ll feel better telling the humans here about it.', None)
            , 'i am sad': ('Maybe you\'ll feel better telling the humans here about it.', None)
            , 'im sad': ('Maybe you\'ll feel better telling the humans here about it.', None)
            , 'you are my only friend': ('Well, that\'s just sad.', None)
            , 'how will one last god kubera end': ('Currygom knows.', None)
            , 'how will one last god kubera end': ('Currygom knows.', None)
            , 'how will olg kubera end': ('Currygom knows.', None)
            , 'how will kubera end': ('Currygom knows.', None)
            , 'are you ignoring me': ('... ...')
            , 'are you ignoring us': ('... ...')
            }
    return bank
